# Local development settings
spring.datasource.url=jdbc:postgresql://localhost:5432/bloodbankdb
spring.datasource.username=postgres
spring.datasource.password=password

# Show detailed logs in dev
logging.level.org.springframework=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

jwt.secret=mySecretKey12345678901234567890123456789012
jwt.expiration=86400000