spring.application.name=Blood_bank
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

app.name=Blood Bank Finder API
app.version=1.0.0
app.author=Aditya Raj

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Blood Bank Finder API
info.app.version=1.0.0
info.app.author=Aditya Raj
info.app.description=Find available blood in nearby blood banks

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}